apiVersion: v1
kind: Pod
metadata:
  name: adSync-core-jenkins
  namespace: jenkins
spec:
  containers:
  - name: maven
    image: maven:3.8.5-openjdk-17
    command:
    - cat
    tty: true
    resources:
      requests:
        memory: "1024Mi"
        cpu: "300m"
      limits:
        memory: "4096Mi"
        cpu: "600m"
    volumeMounts:
      - name: maven-pv
        mountPath: "/root/.m2/repository"   
        subPath: m2
      - name: docker-socket-pv
        mountPath: /var/run/docker.sock  
      - name: docker-pv
        mountPath: /usr/bin/docker
  - name: mysql
    image: mysql:5.7
    env:
    - name: MYSQL_ALLOW_EMPTY_PASSWORD
      value: "1"
    resources:
     requests:
       memory: "1024Mi"
       cpu: "300m"
     limits:
       memory: "2048Mi"
       cpu: "600m"
    ports:
    - name: mysql
      containerPort: 3306
    livenessProbe:
      exec:
        command: ["mysqladmin", "ping"]
      initialDelaySeconds: 30
      periodSeconds: 10 
      timeoutSeconds: 5
    readinessProbe:
      exec:
        # Check we can execute queries over TCP (skip-networking is off).
        command: ["mysql", "-h", "127.0.0.1", "-e", "SELECT 1"]
      initialDelaySeconds: 10
      periodSeconds: 2
      timeoutSeconds: 1
    volumeMounts:
      - name: tmpfs-pv
        mountPath: "/var/lib/mysql"
  - name: docker
    image: google/cloud-sdk:314.0.0-slim
    command:
    - cat
    tty: true
    volumeMounts:
      - name: docker-socket-pv
        mountPath: /var/run/docker.sock   
      - name: docker-pv
        mountPath: /usr/bin/docker
  # initContainers:
  # - name: mysql-init
  #   image: gcr.io/ipay-sl/ipay-txn-processor-test-mysql
  #   command: ["/bin/sh","-c"]
  #   args: ["mv -v /tmp/mysql/*  /var/lib/mysql/"]
  #   volumeMounts:
  #     - name: tmpfs-pv
  #       mountPath: "/var/lib/mysql"
  volumes:
    - name: maven-pv
      persistentVolumeClaim:
       claimName: maven-pv-claim  
    - name: docker-socket-pv
      hostPath:
       path: /var/run/docker.sock
       type: Socket
    - name: docker-pv
      hostPath:
       path: /usr/bin/docker
    - name: tmpfs-pv
      emptyDir:
        medium: Memory
    

